rectorphp/rector-downgrade-php

- rules/DowngradePhp72/NodeManipulator/JsonConstCleaner.php
Use LNumber instead of ConstFetch with Name 0
> Fix invalid identifier 0 on latest php-parser 4.15.1

- composer.json
- rules-tests/DowngradePhp54/Rector/LNumber/DowngradeBinaryNotationRector/DowngradeBinaryNotationRectorTest.php
- rules/DowngradePhp74/Rector/LNumber/DowngradeNumericLiteralSeparatorRector.php
I tried locally and it seems test is working so it should be enabled.
> [DowngradePhp54] Enable skipped test on DowngradeBinaryNotationRectorTest

- rector.php
- rules-tests/DowngradePhp74/Rector/ArrowFunction/ArrowFunctionToAnonymousFunctionRector/Fixture/arrow_function_with_throw.php.inc
- rules/DowngradePhp74/Rector/ArrowFunction/ArrowFunctionToAnonymousFunctionRector.php
Just to make this rule work on its own :+1:
> [Downgrade PHP 7.4] Add return throw to ArrowFunctionToAnonymousFunctionRectorL

- config/set/downgrade-php80.php
@TomasVotruba this is to resolve downgrade build on rector-src:
Downgrade build failure seems unrelated:
```diff
------------------------------------------------------------
Parse error: rector-prefixed-downgraded/vendor/nette/utils/src/Utils/Arrays.php:171
169|      */
170|     public static function grep(array $array, #[\JetBrains\PhpStorm\Language('RegExp')] string $pattern, int $flags = 0) : array
> 171|     {
172|         return Strings::pcre('preg_grep', [$pattern, $array, $flags]);
173|     }
Unexpected '{', expecting variable (T_VARIABLE) in rector-prefixed-downgraded/vendor/nette/utils/src/Utils/Arrays.php on line 171
------------------------------------------------------------
Parse error: rector-prefixed-downgraded/vendor/nette/utils/src/Utils/Strings.php:399
397|      */
398| …
```
> Downgrade Jetbrains\PhpStorm\Language via DowngradeAttributeToAnnotationRector

- config/set/downgrade-php73.php
- rules-tests/DowngradePhp73/Rector/Unset_/DowngradeTrailingCommasInUnsetRector/DowngradeTrailingCommasInUnsetRectorTest.php
- rules-tests/DowngradePhp73/Rector/Unset_/DowngradeTrailingCommasInUnsetRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp73/Rector/Unset_/DowngradeTrailingCommasInUnsetRector/config/configured_rule.php
- rules/DowngradePhp73/Rector/Unset_/DowngradeTrailingCommasInUnsetRector.php
```php
unset($a, $b,);
unset($a, $b);
```
https://3v4l.org/vS0VI
Pretty much like [DowngradeTrailingCommasInFunctionCallsRector](https://github.com/rectorphp/rector-downgrade-php/blob/main/rules/DowngradePhp73/Rector/FuncCall/DowngradeTrailingCommasInFunctionCallsRector.php) but `Unset_` has `->values` instead of `->args`. Both cases could be handled in a single rector.
> Downgrade trailing commas in unset()

- rules-tests/DowngradePhp73/Rector/String_/DowngradeFlexibleHeredocSyntaxRector/Fixture/line_ends_with_newline_or_semicolon.php.inc
- rules/DowngradePhp73/Rector/String_/DowngradeFlexibleHeredocSyntaxRector.php
- rules/DowngradePhp73/Tokenizer/FollowedByNewlineOnlyMaybeWithSemicolonAnalyzer.php
> Prior to PHP 7.3.0, it is very important to note that the line with the closing identifier must contain no other characters, except a semicolon (;).
[PHP manual](https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc)
This works if an indented here/nowdoc is rewritten but not if the source isn't indented.
```php
$needsDowngrade2 = <<<EOS
test
EOS; $z = '';
```
https://getrector.com/demo/14c60416-0504-4b64-ab8b-f7f861892e67 vs. https://getrector.com/demo/06cb930b-d7a5-4e90-9e6d-76a69fad015d
> Fix closing identifier constraints for flexible here doc rector

- rules-tests/DowngradePhp74/Rector/ClassMethod/DowngradeCovariantReturnTypeRector/Fixture/skip_same_return_type.php.inc
- rules-tests/DowngradePhp74/Rector/ClassMethod/DowngradeCovariantReturnTypeRector/Fixture/sub_return_type.php.inc
- rules-tests/DowngradePhp74/Rector/ClassMethod/DowngradeCovariantReturnTypeRector/Source/Handler.php
- rules-tests/DowngradePhp74/Rector/ClassMethod/DowngradeCovariantReturnTypeRector/Source/ResponseInterface.php
- rules-tests/DowngradePhp74/Rector/ClassMethod/DowngradeCovariantReturnTypeRector/Source/TempResponse.php
- rules/DowngradePhp74/Rector/ClassMethod/DowngradeCovariantReturnTypeRector.php
Fixes https://github.com/rectorphp/rector/issues/7768
> [DowngradePhp74] Skip same return type on DowngradeCovariantReturnTypeRector

- rules-tests/DowngradePhp74/Rector/ClassMethod/DowngradeCovariantReturnTypeRector/Fixture/skip_return_non_nullable_override_nullable.php.inc
- rules-tests/DowngradePhp74/Rector/ClassMethod/DowngradeCovariantReturnTypeRector/Source/ReturnNullable.php
- rules/DowngradePhp74/Rector/ClassMethod/DowngradeCovariantReturnTypeRector.php
@TomasVotruba @defunctl  continue of PR:
- https://github.com/rectorphp/rector-downgrade-php/pull/46
nullable parent should be skipped as allowed, see https://3v4l.org/aj0oW#v7.3.17
> [DowngradePhp74] Skip nullable parent on DowngradeCovariantReturnTypeRector

- phpstan.neon
- rules/DowngradePhp56/NodeManipulator/UnpackedArgList.php
- rules/DowngradePhp72/Rector/FuncCall/DowngradeJsonDecodeNullAssociativeArgRector.php
- rules/DowngradePhp73/Rector/FuncCall/SetCookieOptionsArrayToArgumentsRector.php
- rules/DowngradePhp73/Rector/List_/DowngradeListReferenceAssignmentRector.php
- rules/DowngradePhp74/Rector/Array_/DowngradeArraySpreadRector.php
- rules/DowngradePhp74/Rector/FuncCall/DowngradeStripTagsCallWithArrayRector.php
- rules/DowngradePhp80/NodeAnalyzer/UnnamedArgumentResolver.php
- rules/DowngradePhp80/Rector/ArrayDimFetch/DowngradeDereferenceableOperationRector.php
- rules/DowngradePhp80/Rector/Catch_/DowngradeNonCapturingCatchesRector.php
- rules/DowngradePhp80/Rector/Class_/DowngradePropertyPromotionRector.php
- rules/DowngradePhp81/NodeFactory/ArrayMergeFromArraySpreadFactory.php
- rules/DowngradePhp81/Rector/FunctionLike/DowngradeNewInInitializerRector.php
- src/NodeAnalyzer/MethodCallTypeAnalyzer.php
- src/NodeFactory/DoctrineAnnotationFactory.php
- src/NodeManipulator/PropertyDecorator.php
This PR continue of : 
- https://github.com/rectorphp/rector-downgrade-php/pull/52
which lookup parent from `Array_` to get `ClassConst`. 
To  increase performance, this PR add `ClassConst` at `getNodeTypes()` to lookup the `Array_` from its value intead.
> Remove parent attribute usage on DowngradeArraySpreadRector

- rules-tests/DowngradePhp70/Rector/Expression/DowngradeDefineArrayConstantRector/Fixture/skip_first_class_callable.php.inc
- rules/DowngradePhp54/Rector/FuncCall/DowngradeIndirectCallByArrayRector.php
- rules/DowngradePhp55/Rector/ClassConstFetch/DowngradeClassConstantToStringRector.php
- rules/DowngradePhp55/Rector/FuncCall/DowngradeBoolvalRector.php
- rules/DowngradePhp70/Rector/Expression/DowngradeDefineArrayConstantRector.php
- rules/DowngradePhp70/Rector/FuncCall/DowngradeDirnameLevelsRector.php
- rules/DowngradePhp70/Rector/FuncCall/DowngradeSessionStartArrayOptionsRector.php
- rules/DowngradePhp70/Rector/FuncCall/DowngradeUncallableValueCallToCallUserFuncRector.php
- rules/DowngradePhp70/Rector/MethodCall/DowngradeClosureCallRector.php
- rules/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector.php
- rules/DowngradePhp71/Rector/FuncCall/DowngradeIsIterableRector.php
- rules/DowngradePhp71/Rector/StaticCall/DowngradeClosureFromCallableRector.php
- rules/DowngradePhp72/NodeAnalyzer/FunctionExistsFunCallAnalyzer.php
- rules/DowngradePhp72/NodeManipulator/BitwiseFlagCleaner.php
- rules/DowngradePhp72/Rector/FuncCall/DowngradeStreamIsattyRector.php
- rules/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector.php
- rules/DowngradePhp73/Rector/FuncCall/DowngradeIsCountableRector.php
- rules/DowngradePhp73/Rector/FuncCall/DowngradeTrailingCommasInFunctionCallsRector.php
- rules/DowngradePhp73/Rector/FuncCall/SetCookieOptionsArrayToArgumentsRector.php
- rules/DowngradePhp74/Rector/FuncCall/DowngradeStripTagsCallWithArrayRector.php
- rules/DowngradePhp80/Rector/FuncCall/DowngradeNumberFormatNoFourthArgRector.php
- rules/DowngradePhp80/Rector/FuncCall/DowngradeStrContainsRector.php
- rules/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector.php
- rules/DowngradePhp81/NodeManipulator/ObjectToResourceReturn.php
- rules/DowngradePhp81/Rector/FuncCall/DowngradeArrayIsListRector.php
- rules/DowngradePhp81/Rector/FuncCall/DowngradeEnumExistsRector.php
Ref https://github.com/rectorphp/rector-src/pull/3822
> Make use of getArgs()

- .github/workflows/tests.yaml
To show error per fixture https://github.com/rectorphp/rector-downgrade-php/pull/55#discussion_r1193003900
> [CI] Enable zend.assertions ini values in CI

- composer.json
- rules/DowngradePhp71/Rector/String_/DowngradeNegativeStringOffsetToStrlenRector.php
@TomasVotruba @staabm this require PR on rector-src:
- https://github.com/rectorphp/rector-src/pull/3896
this cover next node of: `String_`, `Variable`, `PropertyFetch`, `StaticPropertyFetch`.
for adding `BetterNodeFinder::resolvePreviousNode()` and `BetterNodeFinder::resolveNextNode()` to be merged first.
> [1.0] Use BetterNodeFinder::resolveNextNode() on DowngradeNegativeStringOffsetToStrlenRector

- rules/DowngradePhp70/Rector/FuncCall/DowngradeDirnameLevelsRector.php
- rules/DowngradePhp80/Rector/ClassMethod/DowngradeAbstractPrivateMethodInTraitRector.php
Use `ReflectionResolver` instead.
> [DowngradePhp80] Remove parent attribute on DowngradeAbstractPrivateMethodInTraitRector

- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/method_call_as_arg.php.inc
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/method_call_as_arg2.php.inc
- rules/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector.php
@leoloso  @TomasVotruba continue for quick fix of PR:
- https://github.com/rectorphp/rector-downgrade-php/pull/85
this is to ensure no same issue happen again in the future by refactor `DowngradeArrayKeyFirstLastRector` to cover method call on `end()` or `key()`
Ref https://3v4l.org/TclSB
> [DowngradePhp73] Handle method call as arg on DowngradeArrayKeyFirstLastRector

- rules-tests/DowngradePhp81/Rector/FuncCall/DowngradeArrayIsListRector/Fixture/no_scope_parent_assign_from_func_call.php.inc
- rules/DowngradePhp81/Rector/FuncCall/DowngradeArrayIsListRector.php
- src/NodeAnalyzer/TopStmtAndExprMatcher.php
- src/ValueObject/StmtAndExpr.php
This is part of issue:
- https://github.com/rectorphp/rector/issues/7975
to make downgrade more reliable to lookup Expr in top `StmtsAwareInterface` first, eg: on `If_`, it lookup on `cond`, then if exists, then return its stmt and expr so we can add new stmt before the stmt.
> [Downgrade] Add TopStmtAndExprMatcher

- rules/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector.php
instead of lookup via BetterNodeFinder to resolve current statement, compare via parent Scope instead.
>  [DowngradePhp80] Remove parent lookup on DowngradeMatchToSwitchRector 

- phpstan.neon
- rules/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector.php
- tests/Set/Fixture/match_and_throw_expr.php.inc
Ref https://github.com/rectorphp/rector-src/commit/a8922f7431c9c9188be501107ee7819e0130da4c
We need to downgrade this propperly, to avoid exception as Expr, but as have is as a Stmt.
For now, we can go with the `null` stmt to make the result code at least runnable. 
Any ideas how to handle this better? :)
> Add test case for match + throws

- rules-tests/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector/FixtureEmptyConfig/default_null_not_part_of_union.php.inc
- rules/DowngradePhp72/PhpDoc/NativeParamToPhpDocDecorator.php
Fixes https://github.com/rectorphp/rector/issues/7994
> [DowngradePhp72] Handle crash on default null not part of Union on DowngradeParameterTypeWideningRector

- rules-tests/DowngradePhp73/Rector/ConstFetch/DowngradePhp73JsonConstRector/Fixture/add_throw_on_json_decode_error.php.inc
- rules-tests/DowngradePhp73/Rector/ConstFetch/DowngradePhp73JsonConstRector/Fixture/add_throw_on_json_encode_error.php.inc
- rules-tests/DowngradePhp73/Rector/ConstFetch/DowngradePhp73JsonConstRector/Fixture/in_bitwise.php.inc
- rules/DowngradePhp73/Rector/ConstFetch/DowngradePhp73JsonConstRector.php
- rules/DowngradePhp81/NodeFactory/ArrayMergeFromArraySpreadFactory.php
Add a throwing error behavior after any `json_encode` or `json_decode` function called with the `JSON_THROW_ON_ERROR` flag set, since it will be removed.
This is a partial improvement of removing the `JSON_THROW_ON_ERROR` flag altogether without a proper alternative behavior, but that only works when the flags are directly set in the function call.
If the flags are set from a variable, that would require a much more complex analysis to be 100% accurate, probably beyond Rector actual capabilities.
> feat(DowngradePhp73JsonConstRector): throw behavior

- rules-tests/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector/DowngradeMatchToSwitchRectorTest.php
- rules-tests/DowngradePhp81/Rector/FunctionLike/DowngradeNewInInitializerRector/DowngradeNewInInitializerRectorTest.php
- rules/DowngradePhp81/Rector/FunctionLike/DowngradeNewInInitializerRector.php
After removed `gc_collect_cycles()` on PR:
- https://github.com/rectorphp/rector-src/pull/4472
the `RunTestsInSeparateProcesses` seems no longer needed.
> [Test] Remove RunTestsInSeparateProcesses in tests

- rules/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector.php
`INSIDE_ARRAY_ITEM` attribtue only used once, and by this, this can be removed next on `ContextNodeVisitor`
https://github.com/rectorphp/rector-src/blob/77167c7a1047f430b68f7b1063b5f2cb8dfa9830/packages/NodeTypeResolver/PHPStan/Scope/NodeVisitor/ContextNodeVisitor.php#L56
> [DowngradePhp80] Remove AttributeKey::INSIDE_ARRAY_ITEM usage on DowngradeMatchToSwitchRector

- composer.json
- rules-tests/DowngradePhp81/Rector/FunctionLike/DowngradePureIntersectionTypeRector/Fixture/function_arg_and_return_intersection.php.inc
- rules-tests/DowngradePhp81/Rector/FunctionLike/DowngradePureIntersectionTypeRector/Fixture/function_arg_intersection.php.inc
- rules-tests/DowngradePhp81/Rector/FunctionLike/DowngradePureIntersectionTypeRector/Fixture/function_return_intersection.php.inc
- rules-tests/DowngradePhp81/Rector/FunctionLike/DowngradePureIntersectionTypeRector/Fixture/method_arg_intersection.php.inc
- rules-tests/DowngradePhp81/Rector/FunctionLike/DowngradePureIntersectionTypeRector/Fixture/method_return_intersection.php.inc
@TomasVotruba this is temporary use `dev-main#84b3ea107c6d5b5d369358cdfd7fc6e69d390e9d` from PR:
- https://github.com/rectorphp/rector-src/pull/4598
to update `DowngradePureIntersectionTypeRector` fixtures to use FQCN.
> Update DowngradePureIntersectionTypeRector fixtures to use FQCN

- composer.json
The intersection patch already merged at PR:
- https://github.com/rectorphp/rector-src/pull/4598
so it can use dev-main again.
> Back to require rector/rector-src:dev-main

- phpstan.neon
The notice for complexity somehow just increased 1:
https://github.com/rectorphp/rector-src/actions/runs/5725830338/job/15515089154#step:7:16
```
Run vendor/bin/phpstan
Note: Using configuration file /home/runner/work/rector-src/rector-src/phpstan.neon.
0/285 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
285/285 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
Error: Class cognitive complexity is 61, keep it under 30
------ ------------------------------------------------------------------------- 
Line   rules/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector.php  
------ ------------------------------------------------------------------------- 
41     Class cognitive complexity is 61, keep it under 30                       
------ --------------------------------------------------------------------- …
```
> Fix PHPStan notice on DowngradeMatchToSwitchRector

- rules-tests/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector/Fixture/get_nullable.php.inc
- rules-tests/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector/Fixture/get_nullable_in_trait.php.inc
- rules-tests/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector/Fixture/multiple_call.php.inc
- rules/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector.php
@TomasVotruba when Rector enter different file, the counter should be reset to 0. This is to avoid keep changing counter in the downgrade build and make more reliable run tests between env.
> [DowngradePhp80] Reset counter to 0 when changing file on DowngradeNullsafeToTernaryOperatorRector

- rules/DowngradePhp81/Rector/FuncCall/DowngradeFirstClassCallableSyntaxRector.php
instead of manual check `VariadicPlaceholder`.
> [Downgradephp81] Use $node->isFirstClassCallable() on DowngradeFirstClassCallableSyntaxRector

- rules/DowngradePhp81/NodeFactory/ArrayMergeFromArraySpreadFactory.php
- rules/DowngradePhp81/Rector/Array_/DowngradeArraySpreadStringKeyRector.php
Already called in the rules that uses it.
> [Performance] Remove double validate ArraySpreadAnalyzer::isArrayWithUnpack() on ArrayMergeFromArraySpreadFactory

- .github/workflows/code_analysis.yaml
- .github/workflows/tests.yaml
Current github actions/checkout v3 got error:
```
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_4ecd32f5-c361-435e-b74b-7171ccb18414/3c125ce6-395a-4023-acd8-39fc47eba947.tar.gz. return code: 2.
```
Ref https://github.com/rectorphp/rector-src/actions/runs/6074243601/job/16477779233#step:1:35
It reported at:
- https://github.com/actions/checkout/issues/1448
This PR try to update to github actions/checkout v4.
> Update github actions/checkout from v3 to v4

- rules-tests/DowngradePhp80/Rector/FunctionLike/DowngradeUnionTypeDeclarationRector/Fixture/do_not_change_correct_union_array_docblock_on_param2.php.inc
- rules/DowngradePhp73/Tokenizer/FollowedByNewlineOnlyMaybeWithSemicolonAnalyzer.php
- src/PhpDocDecorator/PhpDocFromTypeDeclarationDecorator.php
Ref https://getrector.com/demo/3754a875-eb9f-4731-a52e-0f1ef8eeb441
Fixes https://github.com/rectorphp/rector/issues/8004
> [DowngradePhp80] Do not change correct union array docblock on DowngradeUnionTypeDeclarationRector

- rules/DowngradePhp74/Rector/FuncCall/DowngradeProcOpenArrayCommandArgRector.php
The `$scope` variable is never used so it can be `AbstractScopeAwareRector` can be replaced with `AbstractRector`
> [DowngradePhp74] use AbstractRector on DowngradeProcOpenArrayCommandArgRector

- rules-tests/DowngradePhp81/Rector/FuncCall/DowngradeHashAlgorithmXxHash/Fixture/skip_hash_not_on_list.php.inc
- rules/DowngradePhp81/Rector/FuncCall/DowngradeHashAlgorithmXxHashRector.php
@malteschlueter @TomasVotruba  this is to fix downgrade error:
```
Run php -d memory_limit=-1 bin/rector process rector-build/bin rector-build/config rector-build/src rector-build/packages rector-build/rules rector-build/vendor --config build/config/config-downgrade.php --ansi --no-diffs
0/2542 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
510/2542 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  20%
1020/2542 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  40%
1530/2542 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  60%
2040/2542 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]  80%
[ERROR] Could not process                                                      
"/home/runner/work/rector-src/rector-src/rector-build/src/Util/FileHash
er.php" file, due to:                                                  
"System error: "Look at …
```
> [DowngradePhp81] Fix algo not on list on DowngradeHashAlgorithmXxHashRector

- rules-tests/DowngradePhp80/Rector/MethodCall/DowngradeReflectionGetAttributesRector/Fixture/class_is_nullable.php.inc
- rules/DowngradePhp73/Rector/List_/DowngradeListReferenceAssignmentRector.php
- rules/DowngradePhp74/Rector/ClassMethod/DowngradeContravariantArgumentTypeRector.php
- rules/DowngradePhp74/Rector/ClassMethod/DowngradeCovariantReturnTypeRector.php
- rules/DowngradePhp74/Rector/Interface_/DowngradePreviouslyImplementedInterfaceRector.php
- rules/DowngradePhp80/Rector/Class_/DowngradePropertyPromotionRector.php
- rules/DowngradePhp80/Rector/MethodCall/DowngradeReflectionGetAttributesRector.php
Currently Rector will do nothing which causes errors in PHP 7.4, see https://getrector.com/demo/8519d581-e93f-4d8b-8de4-956051503436.
The thing is that the following condition will result in a [`TrinaryLogic::createMaybe()`](https://github.com/phpstan/phpstan-src/blob/82364923b52079d20c23d38b8db2a1f9d2bdbfaf/src/Type/ObjectType.php#L398) but the method `isObjectType` returns `true` only on a `TrinaryLogic::YES`
https://github.com/rectorphp/rector-downgrade-php/blob/2d20783f344dec1895e19d2797d4c3b903b4f3cb/rules/DowngradePhp80/Rector/MethodCall/DowngradeReflectionGetAttributesRector.php#L83
Because of that I added the explicit comparison with the `ReflectionClass`.
> DowngradeTo74: Fix rector rule if ReflectionClass is nullable

- rules/DowngradePhp80/Rector/MethodCall/DowngradeReflectionGetAttributesRector.php
@malteschlueter Per PR on rector-src
- https://github.com/rectorphp/rector-src/pull/5224
instanceof ReflectionClass no longer needed as it is instanceof Reflector.
> Remove unnecessary check ReflectionClass on DowngradeReflectionGetAttributesRector

- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/possible_non_array_or_object_array_key_first.php.inc
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/possible_non_array_or_object_array_key_last.php.inc
- rules/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector.php
@leoloso this should fix https://github.com/rectorphp/rector/issues/8321 , only check next stmt is If_ with it inside `BooleanOr` is enough check I think, and only check `is_array()` is ok, since passed data will need to be array on check `array_key_last()` and `array_key_first()`  except we got more complex if usage on symfony :)
> [DowngradePhp73] Handle next if with BooleanOr condition that cause possible non-array data on DowngradeArrayKeyFirstLastRector

- rules-tests/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector/Fixture/call_anonymous_function.php.inc
- rules-tests/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector/Fixture/function_call.php.inc
- rules-tests/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector/Fixture/match_as_arg.php.inc
- rules-tests/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector/Fixture/method_call.php.inc
- rules-tests/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector/Fixture/static_call.php.inc
- rules/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector.php
@ian-zunderdorp this should fix https://github.com/rectorphp/rector/issues/8369
I found that convert match as arg as invokable closure as your suggestion seems ok. let's try it.
> [DowngradePhp80] Handle match as arg on DowngradeMatchToSwitchRector

- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/array_key_last.php.inc
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/cast_array_key_last_value.php.inc
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/double_cast.php.inc
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/inside_if_cond.php.inc
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/keep_inside_else.php.inc
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/keep_inside_if.php.inc
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/method_call_as_arg.php.inc
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/possible_non_array_or_object_array_key_last.php.inc
- rules/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector.php
@kapersoft @TomasVotruba here the proper solution to fix https://github.com/rectorphp/rector/issues/8531
> [DowngradePhp73] Ensure reset() after go to end() array on DowngradeArrayKeyFirstLastRector

- rules-tests/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector/Fixture/return_throw_ternary.php.inc
- rules/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector.php
Fixes https://github.com/rectorphp/rector/issues/8671
> [DowngradePhp80] Handle return throw ternary on DowngradeThrowExprRector

- rules-tests/DowngradePhp81/Rector/FunctionLike/DowngradeNewInInitializerRector/Fixture/in_abstract_method.php.inc
- rules/DowngradePhp81/Rector/FunctionLike/DowngradeNewInInitializerRector.php
For usage of interface method, yes, all interface method are abstract, it should not append stmts, only change param.
Fixes https://github.com/rectorphp/rector/issues/8810
> [DowngradePhp81] Handle abstract method on DowngradeNewInInitializerRector

- composer.json
- rules/DowngradePhp72/Rector/FuncCall/DowngradeStreamIsattyRector.php
- rules/DowngradePhp74/Rector/Array_/DowngradeArraySpreadRector.php
- rules/DowngradePhp80/Rector/Catch_/DowngradeNonCapturingCatchesRector.php
- rules/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector.php
- rules/DowngradePhp81/Rector/Array_/DowngradeArraySpreadStringKeyRector.php
- rules/DowngradePhp81/Rector/Property/DowngradeReadonlyPropertyRector.php
Ref https://github.com/rectorphp/rector-src/pull/6425
> Make use of AbstractRector and scope fetcher

- rules-tests/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector/Fixture/fn_return_throw.php.inc
- rules/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector.php
Ref https://github.com/rectorphp/rector-src/actions/runs/11936682512/job/33270880890
>  Fix downgrade throw on ArrowFunction return 

- rules/DowngradePhp80/Rector/StaticCall/DowngradePhpTokenRector.php
Ref https://github.com/rectorphp/rector-src/pull/6431#issuecomment-2489079041
> Skip internal PhpParser TokenPolyfill on DowngradePhpTokenRector

- rules-tests/DowngradePhp80/Rector/StaticCall/DowngradePhpTokenRector/Fixture/skip_extends_internal_php_parser_token.php.inc
Add test fixture for patch:
- https://github.com/rectorphp/rector-downgrade-php/pull/239
- https://github.com/rectorphp/rector-downgrade-php/pull/240
> Add fixture test for skip internal php php-parser token on DowngradePhpTokenRector

- rules-tests/DowngradePhp81/Rector/FunctionLike/DowngradeNewInInitializerRector/Fixture/new_not_promoted.php.inc
- rules/DowngradePhp81/Rector/FunctionLike/DowngradeNewInInitializerRector.php
- tests/Issues/DowngradeNewInArrayInitializerPromotion/Fixture/new_in_array.php.inc
- tests/Issues/DowngradeNullableInitialization/DowngradeNullableInitializationTest.php
- tests/Issues/DowngradeNullableInitialization/Fixture/add_nullable_initialization.php.inc
- tests/Issues/DowngradeNullableInitialization/config/configured_rule.php
Fixes https://github.com/rectorphp/rector-doctrine/issues/352
> [Downgrade][Php81][Php80] Handle nullable downgrade initialization on use DowngradeNewInInitializerRector+DowngradePropertyPromotionRector

- rules/DowngradePhp81/Rector/Array_/DowngradeArraySpreadStringKeyRector.php
To avoid crash like in 
- https://github.com/rectorphp/rector/issues/8907
> Avoid using ->isArray()->yes() usage on getKeyType() usage next

- rules-tests/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector/Fixture/reprint_same_line.php.inc
- rules-tests/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector/Fixture/skip_allow_dynamic_properties.php.inc
- rules/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector.php
Fixes https://github.com/rectorphp/rector/issues/8908
> [DowngradePhp80] Skip native AllowDynamicProperties attribute on DowngradeAttributeToAnnotationRector

- rules/DowngradePhp73/Rector/FuncCall/DowngradeTrailingCommasInFunctionCallsRector.php
- rules/DowngradePhp73/Rector/Unset_/DowngradeTrailingCommasInUnsetRector.php
- rules/DowngradePhp80/Rector/ClassMethod/DowngradeTrailingCommasInParamUseRector.php
Ref PR:
- https://github.com/rectorphp/rector-src/pull/6491
the orig node set to null already cover it.
> Remove no longer needed FUNC_ARGS_TRAILING_COMMA attribute usage marker on downgrade rules

- rules/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector.php
- tests/Issues/DowngradeAttributeSameLineWithPromotion/DowngradeAttributeSameLineWithPromotionTest.php
- tests/Issues/DowngradeAttributeSameLineWithPromotion/Fixture/fixture.php.inc
- tests/Issues/DowngradeAttributeSameLineWithPromotion/config/configured_rule.php
On php 8.x, `#[\Attribute]final class WithSameLine` is valid code, while on php 7, it got error, so it needs to mark as comment, with get line via token, per recommended at:
- https://github.com/nikic/PHP-Parser/issues/1043#issuecomment-2496130277
> [DowngradePhp80] Downgrade same line attribute on non-removed attribute on DowngradeAttributeToAnnotationRector

- config/set/downgrade-php84.php
- config/set/level/down-to-php83.php
- rules-tests/DowngradePhp84/Rector/MethodCall/DowngradeNewMethodCallWithoutParenthesesRector/DowngradeNewMethodCallWithoutParenthesesRectorTest.php
- rules-tests/DowngradePhp84/Rector/MethodCall/DowngradeNewMethodCallWithoutParenthesesRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp84/Rector/MethodCall/DowngradeNewMethodCallWithoutParenthesesRector/Fixture/skip_already_parentheses.php.inc
- rules-tests/DowngradePhp84/Rector/MethodCall/DowngradeNewMethodCallWithoutParenthesesRector/config/configured_rule.php
- rules/DowngradePhp84/Rector/MethodCall/DowngradeNewMethodCallWithoutParenthesesRector.php
- src/Set/ValueObject/DowngradeLevelSetList.php
- src/Set/ValueObject/DowngradeSetList.php
To downgrade new method call without parentheses for php 8.4 https://wiki.php.net/rfc/new_without_parentheses
Ref to allow feature https://github.com/rectorphp/rector/issues/8701, the downgrade rule need to exists on the first place.
> [DowngradePhp84] Add DowngradeNewMethodCallWithoutParenthesesRector

- rules-tests/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector/Fixture/short_circuit.php.inc
- rules-tests/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector/Fixture/short_circuit.php2.inc
- rules-tests/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector/Fixture/short_circuit3.php.inc
- rules-tests/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector/Fixture/short_circuit4.php.inc
- rules-tests/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector/Fixture/short_circuit5.php.inc
- rules/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector.php
Fixes https://github.com/rectorphp/rector/issues/8915
> [DowngradePhp80] Handle short circuit on DowngradeNullsafeToTernaryOperatorRector

- rules-tests/DowngradePhp73/Rector/Unset_/DowngradeTrailingCommasInUnsetRector/Fixture/fixture.php.inc
- rules/DowngradePhp73/Rector/FuncCall/DowngradeTrailingCommasInFunctionCallsRector.php
- rules/DowngradePhp73/Rector/Unset_/DowngradeTrailingCommasInUnsetRector.php
- rules/DowngradePhp73/Tokenizer/TrailingCommaRemover.php
- rules/DowngradePhp80/Rector/ClassMethod/DowngradeTrailingCommasInParamUseRector.php
- rules/DowngradePhp84/Rector/MethodCall/DowngradeNewMethodCallWithoutParenthesesRector.php
To avoid issue like in `DowngradeFlexibleHeredocSyntaxRector` when combined like in:
- https://github.com/rectorphp/rector-downgrade-php/pull/256
- https://github.com/rectorphp/rector-downgrade-php/pull/257
- https://github.com/rectorphp/rector-downgrade-php/pull/258
but for function call and unset, so avoid reprint when possible.
> Remove trailing comma by token instead of set origNode to null

- config/set/downgrade-php84.php
- rules-tests/DowngradePhp84/Rector/FuncCall/DowngradeRoundingModeEnumRector/DowngradeRoundingModeEnumRectorTest.php
- rules-tests/DowngradePhp84/Rector/FuncCall/DowngradeRoundingModeEnumRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp84/Rector/FuncCall/DowngradeRoundingModeEnumRector/Fixture/from_use.php.inc
- rules-tests/DowngradePhp84/Rector/FuncCall/DowngradeRoundingModeEnumRector/Fixture/no_namespace.php.inc
- rules-tests/DowngradePhp84/Rector/FuncCall/DowngradeRoundingModeEnumRector/Fixture/skip_indirect_use_of_roundin_mode.php.inc
- rules-tests/DowngradePhp84/Rector/FuncCall/DowngradeRoundingModeEnumRector/config/configured_rule.php
- rules/DowngradePhp84/Rector/FuncCall/DowngradeRoundingModeEnumRector.php
Downgrade rule for https://github.com/rectorphp/rector-src/pull/6369
> [DowngradePhp84] Downgrade RoundingMode enum

- config/set/downgrade-php82.php
- rules-tests/DowngradePhp82/Rector/FuncCall/DowngradeIteratorCountToArrayRector/DowngradeIteratorCountToArrayRectorTest.php
- rules-tests/DowngradePhp82/Rector/FuncCall/DowngradeIteratorCountToArrayRector/Fixture/possible_not_traversable.php.inc
- rules-tests/DowngradePhp82/Rector/FuncCall/DowngradeIteratorCountToArrayRector/Fixture/skip_already_has_object_type.php.inc
- rules-tests/DowngradePhp82/Rector/FuncCall/DowngradeIteratorCountToArrayRector/Fixture/skip_already_traversable.php.inc
- rules-tests/DowngradePhp82/Rector/FuncCall/DowngradeIteratorCountToArrayRector/config/configured_rule.php
- rules/DowngradePhp82/Rector/FuncCall/DowngradeIteratorCountToArrayRector.php
see https://www.php.net/manual/en/migration82.other-changes.php#migration82.other-changes.functions.spl
see https://3v4l.org/TPW7a#v8.1.31 on php 8.1, parameter only accept Traversable, so array needs to be converted to `ArrayIterator` first, see see https://3v4l.org/YAeZD#v8.1.31
> [DowngradePhp82] Add DowngradeIteratorCountToArrayRector

- rules/DowngradePhp80/Rector/Expression/DowngradeMatchToSwitchRector.php
- tests/Set/Fixture/match_in_binary_op.php.inc
- tests/Set/Fixture/match_maintains_return_condition.php.inc
- adds a new fixture for the switch to match statement rule in the downgrade to PHP 7.2 test
- adds changes to the `DowngradeMatchToSwitchRector` rule.
Currently this rule breaks code where the match statement exists within a binary operation. For example:
```php
public function run($value, $booleanFlag)
{
return match (true) {
$value === 2 => true,
default => false,
} && $booleanFlag;
}
```
would become
```php
public function run($value, $booleanFlag)
{
switch (true) {
case $value === 2:
return true;
default:
return false;
}
}
```
This would cause conditions related to the return statement to be lost. [This happened in the Rector Laravel project](https://github.com/driftingly/rector-laravel/issues/287). For now I've just separated the match statement and the binary op, but it would be …
> Fix for Match to Switch when inside binary operation

- rules-tests/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector/Fixture/no_isset_on_expr.php.inc
- rules/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector.php
Hello
Here is the fix proposed in the [DowngradeThrowExprRector logical error](https://github.com/rectorphp/rector-downgrade-php/issues/264) issue. 
When downgrading a coalesce operator that uses throw, there is a logical error in how the condition is generated. In the current implementation, the exception is thrown when the left-hand side is not null, but it should be thrown when the left-hand side is null.
> Fix logical comparision

- rules/DowngradePhp72/NodeManipulator/BitwiseFlagCleaner.php
- src/PhpDocDecorator/PhpDocFromTypeDeclarationDecorator.php
ref https://github.com/rectorphp/rector/pull/8990/files#diff-6a4a6fe9ef9b7755c813ac48865f8dd16de0bff4ff4140b9f707b3ffa8e81e58
> Fix php 8.4 compatible code on BitwiseFlagCleaner

- rules-tests/DowngradePhp74/Rector/ArrowFunction/ArrowFunctionToAnonymousFunctionRector/Fixture/no_params_duplicated_in_use.php.inc
- rules/DowngradePhp74/Rector/ArrowFunction/ArrowFunctionToAnonymousFunctionRector.php
I hit an issue today in downgrading some Laravel code.  
The `ArrowFunctionToAnonymousFunctionRector` rule would take this function 
```
fn ($deferred) => app(DeferredCallbackCollection::class)[] = $deferred
```
and transform it to this
```
function ($deferred) use ($deferred) {
return app(DeferredCallbackCollection::class)[] = $deferred;
}
```
and this would result in a PHP error
> Fatal error: Cannot use lexical variable $deferred as a parameter name in <file_path>
My patch works well for solving my problem but if there's a better way to fix this that would be great too.
Thanks for your hard work!
> Check for variable name in parameters before adding to uses

- rules/DowngradePhp72/Rector/ConstFetch/DowngradePhp72JsonConstRector.php
- rules/DowngradePhp73/Rector/ConstFetch/DowngradePhp73JsonConstRector.php
- rules/DowngradePhp74/Rector/MethodCall/DowngradeReflectionGetTypeRector.php
In all three cases, the problem existed because some functions did not actually change nodes in a way that would result in a code change, they just added attributes to inner statements or expressions so that other functions could work on the code, but they still returned a node value as though it had been changed. I modified this so that these functions did not return a node. I also changed their name as they were called `refactorXXX` and no refactor was actually done in these functions, so I used what I think are more appropriate names
> Fix rules that were applied even if no actual change was made

- rules-tests/DowngradePhp80/Rector/FunctionLike/DowngradeUnionTypeDeclarationRector/Fixture/override_from_interface.php.inc
- rules-tests/DowngradePhp80/Rector/FunctionLike/DowngradeUnionTypeDeclarationRector/Source/Foo1.php
- rules-tests/DowngradePhp80/Rector/FunctionLike/DowngradeUnionTypeDeclarationRector/Source/Foo2.php
- rules-tests/DowngradePhp80/Rector/FunctionLike/DowngradeUnionTypeDeclarationRector/Source/FooInterface.php
- rules-tests/DowngradePhp80/Rector/FunctionLike/DowngradeUnionTypeDeclarationRector/Source/SomeInterface.php
- src/PhpDocDecorator/PhpDocFromTypeDeclarationDecorator.php
Fixes https://github.com/rectorphp/rector/issues/9121
> [DowngradePhp80] Handle union implements method from interface on DowngradeUnionTypeDeclarationRector

- rules-tests/DowngradePhp80/Rector/Instanceof_/DowngradeInstanceofStringableRector/Fixture/exactly_object_type.php.inc
- rules-tests/DowngradePhp80/Rector/Instanceof_/DowngradeInstanceofStringableRector/Fixture/fixture.php.inc
- rules/DowngradePhp80/Rector/Instanceof_/DowngradeInstanceofStringableRector.php
The `method_exists()` can pass string value on first argument, see different https://3v4l.org/7prLj so `is_object()` is needed.
> Add is_object() on DowngradeInstanceofStringableRector when possibly not object type

- rules/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector.php
- rules/DowngradePhp80/Rector/ClassMethod/DowngradeRecursiveDirectoryIteratorHasChildrenRector.php
- rules/DowngradePhp80/Rector/ClassMethod/DowngradeStringReturnTypeOnToStringRector.php
- rules/DowngradePhp80/Rector/FuncCall/DowngradeNumberFormatNoFourthArgRector.php
- rules/DowngradePhp80/Rector/MethodCall/DowngradeReflectionClassGetConstantsFilterRector.php
- rules/DowngradePhp80/Rector/MethodCall/DowngradeReflectionPropertyGetDefaultValueRector.php
- rules/DowngradePhp81/Rector/FuncCall/DowngradeArrayIsListRector.php
- rules/DowngradePhp81/Rector/FuncCall/DowngradeHashAlgorithmXxHashRector.php
Ref PR:
- https://github.com/rectorphp/rector-src/pull/6875
> Directly use isName(s) and getName() on rector rules

- config/set/downgrade-php85.php
- config/set/level/down-to-php84.php
- rules-tests/DowngradePhp85/Rector/FuncCall/DowngradeArrayFirstLastRector/DowngradeArrayFirstLastRectorTest.php
- rules-tests/DowngradePhp85/Rector/FuncCall/DowngradeArrayFirstLastRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp85/Rector/FuncCall/DowngradeArrayFirstLastRector/Fixture/skip_different_func_call.php.inc
- rules-tests/DowngradePhp85/Rector/FuncCall/DowngradeArrayFirstLastRector/config/configured_rule.php
- rules/DowngradePhp74/Rector/Array_/DowngradeArraySpreadRector.php
- rules/DowngradePhp85/Rector/FuncCall/DowngradeArrayFirstLastRector.php
- src/Set/ValueObject/DowngradeLevelSetList.php
- src/Set/ValueObject/DowngradeSetList.php
Ref 
- https://github.com/rectorphp/rector/issues/9158
- https://github.com/rectorphp/rector-src/pull/6900
for downgrade the code.
> [DowngradePhp85] Add DowngradeArrayFirstLastRector

- config/set/downgrade-php83.php
- rules-tests/DowngradePhp82/Rector/Class_/DowngradeReadonlyClassRector/Fixture/skip_anonymous_class.php.inc
- rules-tests/DowngradePhp83/Rector/Class_/DowngradeReadonlyAnonymousClassRector/DowngradeReadonlyAnonymousClassRectorTest.php
- rules-tests/DowngradePhp83/Rector/Class_/DowngradeReadonlyAnonymousClassRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp83/Rector/Class_/DowngradeReadonlyAnonymousClassRector/Fixture/skip_named_class.php.inc
- rules-tests/DowngradePhp83/Rector/Class_/DowngradeReadonlyAnonymousClassRector/Fixture/with_parentheses.php.inc
- rules-tests/DowngradePhp83/Rector/Class_/DowngradeReadonlyAnonymousClassRector/config/configured_rule.php
- rules/DowngradePhp82/NodeManipulator/DowngradeReadonlyClassManipulator.php
- rules/DowngradePhp83/Rector/Class_/DowngradeReadonlyAnonymousClassRector.php
Ref issue and PR:
- https://github.com/rectorphp/rector/issues/9151
- https://github.com/rectorphp/rector-src/pull/6916
This share logic between DowngradePhp82 `DowngradeReadonlyClassRector`, which moved the logic to: `DowngradeReadonlyClassManipulator` service, with anonymous check for both rules so can run by rule:
- Php82 `DowngradeReadonlyClassRector`: skip anonymous, downgrade normal class
- Php83 `DowngradeReadonlyAnonymousClassRector`: skip normal class, downgrade anonymous class.
> [DowngradePhp83] Add DowngradeReadonlyAnonymousClassRector

- config/set/downgrade-php83.php
- rules-tests/DowngradePhp83/Rector/ClassConstFetch/DowngradeDynamicClassConstFetchRector/DowngradeDynamicClassConstFetchRectorTest.php
- rules-tests/DowngradePhp83/Rector/ClassConstFetch/DowngradeDynamicClassConstFetchRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp83/Rector/ClassConstFetch/DowngradeDynamicClassConstFetchRector/Fixture/skip_named_class_const_fetch.php.inc
- rules-tests/DowngradePhp83/Rector/ClassConstFetch/DowngradeDynamicClassConstFetchRector/config/configured_rule.php
- rules/DowngradePhp83/Rector/ClassConstFetch/DowngradeDynamicClassConstFetchRector.php
Ref https://github.com/rectorphp/rector/issues/9149
Before create the rule upgrade feature, this rule to cover downgrade rule first .
> [DowngradePhp83] Add DowngradeDynamicClassConstFetchRector

- rules/DowngradePhp80/NodeAnalyzer/NamedToUnnamedArgs.php
- rules/DowngradePhp80/NodeAnalyzer/UnnamedArgumentResolver.php
- tests/Issues/DowngradeNamedTrailing/DowngradeNamedTrailingTest.php
- tests/Issues/DowngradeNamedTrailing/Fixture/fixture.php.inc
- tests/Issues/DowngradeNamedTrailing/config/configured_rule.php
Fixes https://github.com/rectorphp/rector/issues/9187
Ref https://getrector.com/demo/dd085b66-d609-4add-b44c-d4eb8072a3e5
> [DowngradePhp80/Php73] Handle comma removed on combination DowngradeNamedArgumentRector + DowngradeTrailingCommasInFunctionCallsRector

- tests/Set/Fixture/named_argument_trailing_comma2.php.inc
- tests/Set/Fixture/named_argument_trailing_comma3.php.inc
- tests/Set/Fixture/named_argument_trailing_comma4.php.inc
Ensure future patch not cause regression.
> [Test] Add more test fixture for downgrade named argument with trailing comma

- rules-tests/DowngradePhp80/Rector/MethodCall/DowngradeNamedArgumentRector/Fixture/remove_from_unknown_type.php.inc
- rules/DowngradePhp80/Rector/MethodCall/DowngradeNamedArgumentRector.php
Sometimes the named args is used on a variable without any type, like in latest illuminate/contaienr 12.18.x
See https://github.com/illuminate/container/commit/ff9dde2c8dce16ea9ecf0418095749311240aff9
In that case, we cannot leak this named variable further. All we can do is to take a guess, that value is used on the right location and remove it :+1:
> Add support for unknown types in DowngradeNamedArgumentRector

- rules-tests/DowngradePhp81/Rector/StmtsAwareInterface/DowngradeSetAccessibleReflectionPropertyRector/Fixture/on_return.php.inc
- rules/DowngradePhp81/Rector/StmtsAwareInterface/DowngradeSetAccessibleReflectionPropertyRector.php
Ref https://github.com/rectorphp/rector-src/pull/7085#pullrequestreview-3046393513
> [DowngradePhp81] Handle on return on DowngradeSetAccessibleReflectionPropertyRector

- rules-tests/DowngradePhp81/Rector/FuncCall/DowngradeHashAlgorithmXxHash/Fixture/skip_check_version_compare_on_if.php.inc
- rules/DowngradePhp81/Rector/FuncCall/DowngradeHashAlgorithmXxHashRector.php
@kkmuffme this continue of PR:
- https://github.com/rectorphp/rector-downgrade-php/pull/307
to handle `version_compare` in if.
Fixes https://github.com/rectorphp/rector/issues/9327
> [DowngradePhp81] Skip check version_compare with if on DowngradeHashAlgorithmXxHashRector (part 3)

- rules-tests/DowngradePhp81/Rector/Property/DowngradeReadonlyPropertyRector/Fixture/promoted_property.php.inc
- rules-tests/DowngradePhp81/Rector/Property/DowngradeReadonlyPropertyRector/Fixture/readonly_implicit_property_promotion.php.inc
- rules/DowngradePhp81/Rector/Property/DowngradeReadonlyPropertyRector.php
- tests/Issues/DowngradeReadonlyClassPropertyToPhp80/Fixture/fixture.php.inc
see https://phpstan.org/r/7fe0ce63-8d29-4f53-b1c6-5a05c3d31b74
The `@readonly` flag will warn user when user want to change property of promotion.
> [DowngradePhp81] Add @readonly doc on property promotion readonly

- rules-tests/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector/Fixture/override_and_sensitive_parameters.php.inc
- rules/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector.php
```diff
-    public function run(#[\SensitiveParameter] bool $param) {
+    public function run(#[\SensitiveParameter]
+ bool $param) 
``` 
Fixes https://github.com/rectorphp/rector/issues/9355
> [DowngradePhp80] Register Override and SensitiveParameter to skipped attributes on DowngradeAttributeToAnnotationRector

- rules-tests/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector/Fixture/override_and_sensitive_parameters.php.inc
- rules-tests/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector/Fixture/skip_already_newlined_override_and_sensitive_parameters.php.inc
- rules/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector.php
@kkmuffme This is 3rd time try, as I just bumped php-scoper to latest 0.18.17 on rector-src dev-main
- https://github.com/rectorphp/rector-src/pull/7230
> Re-skip Override and SensitiveParameter  part 3

- rules/DowngradePhp81/Rector/Property/DowngradeReadonlyPropertyRector.php
- rules/DowngradePhp85/Rector/Class_/DowngradeFinalPropertyPromotionRector.php
- tests/Issues/DowngradeReadonlyClassPropertyToPhp80/Fixture/fixture.php.inc
Reprint may be make it pretty, but got loss the information tokens which may be used by other rules. This is less pretty for print doc under ClassMethod, but safer.
Ref https://github.com/rectorphp/rector-downgrade-php/pull/316#pullrequestreview-3196482242
The better possible solution is to add "new line" on each param when we are going to add docblock, but that will be in separate PR :)
> Avoid reprint whole ClassMethod on DowngradeReadonlyPropertyRector

- rules-tests/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector/Fixture/attribute_same_line.php.inc
- rules-tests/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector/Fixture/with_override.php.inc
- rules/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector.php
@kkmuffme Let's try this one by one, start with `Override` per use first use case. If it on single line, it enter to new line to mark as comment.
> [DowngradePhp80] Skip Override attribute on DowngradeAttributeToAnnotationRector
