- composer.json
- config/set/downgrade-php80.php
- docs/rector_rules_overview.md
- packages/Set/ValueObject/DowngradeLevelSetList.php
- packages/Set/ValueObject/DowngradeSetList.php
- tests/Set/DownToPhp72Test.php
- tests/Set/Fixture/static_property.php.inc
- tests/Set/config/configured_rule.php
@TomasVotruba this is move DowngradeSetList and DowngradeLevelSetList here.
> Move DowngradeSetList and DowngradeLevelSetList here

- config/config.php
> add missing config

- config/set/downgrade-php81.php
- src/DowngradePhp81/Rector/FuncCall/DowngradeEnumExistsRector.php
- src/DowngradePhp81/snippet/enum_exists_closure.php.inc
- tests/DowngradePhp81/Rector/FuncCall/DowngradeEnumExistsRector/DowngradeEnumExistsRectorTest.php
- tests/DowngradePhp81/Rector/FuncCall/DowngradeEnumExistsRector/Fixture/fixture.php.inc
- tests/DowngradePhp81/Rector/FuncCall/DowngradeEnumExistsRector/Fixture/no_second_arg.php.inc
- tests/DowngradePhp81/Rector/FuncCall/DowngradeEnumExistsRector/Fixture/second_arg_false.php.inc
- tests/DowngradePhp81/Rector/FuncCall/DowngradeEnumExistsRector/Fixture/skip_different_function.php.inc
- tests/DowngradePhp81/Rector/FuncCall/DowngradeEnumExistsRector/config/configured_rule.php
Fixes https://github.com/rectorphp/rector-downgrade-php/issues/11
> [DowngradePhp81] Add DowngradeEnumExistsRector

- docs/rector_rules_overview.md
Add rector rule DowngradeEnumExistsRector to docs
> [DowngradeEnumExistsRector] Add rector rule to docs

- rules-tests/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector/Fixture/return_throw_expr.php.inc
- rules/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector.php
Ref https://github.com/rectorphp/rector-src/actions/runs/3593996364/jobs/6051685236#step:14:71
> [DowngradePhp80] Handle return throw on DowngradeThrowExprRector

- config/set/downgrade-php80.php
- phpstan.neon
To avoid unnecessary manual register on build config 
https://github.com/rectorphp/rector-src/blob/d2064068055fb25da2c245515a6c6260fbe6a597/build/config/config-downgrade.php#L21-L23
> [DowngradePhp80] Register DowngradeEnumToConstantListClassRector to downgrade-php80 config set

- config/set/downgrade-php74.php
- rules-tests/DowngradePhp74/Rector/FuncCall/DowngradeProcOpenArrayCommandArgRector/DowngradeProcOpenArrayCommandArgRectorTest.php
- rules-tests/DowngradePhp74/Rector/FuncCall/DowngradeProcOpenArrayCommandArgRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp74/Rector/FuncCall/DowngradeProcOpenArrayCommandArgRector/Fixture/non_variable.php.inc
- rules-tests/DowngradePhp74/Rector/FuncCall/DowngradeProcOpenArrayCommandArgRector/Fixture/skip_already_string.php.inc
- rules-tests/DowngradePhp74/Rector/FuncCall/DowngradeProcOpenArrayCommandArgRector/config/configured_rule.php
- rules/DowngradePhp74/Rector/FuncCall/DowngradeProcOpenArrayCommandArgRector.php
Ref https://github.com/rectorphp/rector/actions/runs/3595282255/jobs/6054584145#step:6:9
> [DowngradePhp74] Add DowngradeProcOpenArrayCommandArgRector

- rules-tests/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector/Fixture/jetbrains_param.php.inc
- rules/DowngradePhp80/Rector/Class_/DowngradeAttributeToAnnotationRector.php
Fixes regression in ECS created by inlining params and https://github.com/nette/utils/pull/277
> [PHP 8.0] Remove attributes, to avoid commenting code

- composer.json
- docs/rector_rules_overview.md
Per discussion on https://github.com/rectorphp/rector/issues/7752#issuecomment-1413397028
> Remove check-markdown command from composer fix-cs and composer docs

- phpstan.neon
- rules/DowngradePhp54/Rector/FunctionLike/DowngradeCallableTypeDeclarationRector.php
- rules/DowngradePhp70/Rector/FunctionLike/DowngradeThrowableTypeDeclarationRector.php
- rules/DowngradePhp71/Rector/FunctionLike/DowngradeIterablePseudoTypeDeclarationRector.php
- rules/DowngradePhp72/Rector/FunctionLike/DowngradeObjectTypeDeclarationRector.php
- rules/DowngradePhp80/Rector/ClassMethod/DowngradeStaticTypeDeclarationRector.php
- rules/DowngradePhp80/Rector/FunctionLike/DowngradeMixedTypeDeclarationRector.php
- src/PhpDocDecorator/PhpDocFromTypeDeclarationDecorator.php
Ref https://github.com/rectorphp/rector/commit/db9dc03ef14b673a2bd731ff53a321f2db515f45#diff-483138b478ec7484778bb7500356c1eac1109abbb27a6ecb2ebe65c6104d8a5b
> Fix DowngradeMixedTypeDeclarationRector to return node on changed

- phpstan.neon
- rules-tests/DowngradePhp74/Rector/Array_/DowngradeArraySpreadRector/Fixture/on_class_constant.php.inc
- rules/DowngradePhp74/Rector/Array_/DowngradeArraySpreadRector.php
see https://github.com/easy-coding-standard/easy-coding-standard/actions/runs/4488537507/jobs/7893263863#step:11:61
> [DowngradePhp74] Handle DowngradeArraySpreadRector on class constant

- phpstan.neon
- rules/DowngradePhp72/Rector/FuncCall/DowngradeJsonDecodeNullAssociativeArgRector.php
- rules/DowngradePhp80/Rector/MethodCall/DowngradeNamedArgumentRector.php
- src/PhpDocDecorator/PhpDocFromTypeDeclarationDecorator.php
see https://github.com/rectorphp/rector-src/actions/runs/4883159671/jobs/8714128968?pr=3730
> [PHPStan] Fix PHPStan notice Attribute must have all names explicitly defined

- docs/rector_rules_overview.md
- phpstan.neon
- rules/DowngradePhp71/Rector/List_/DowngradeKeysInListRector.php
- Remove PARENT_NODE from DowngradeKeysInListRector
- misc
> Remove PARENT_NODE from DowngradeKeysInListRector

- phpstan.neon
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/inside_if_cond.php.inc
- rules/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector.php
- src/NodeAnalyzer/StmtMatcher.php
Fixes https://github.com/rectorphp/rector-src/actions/runs/5119583188/jobs/9205317992
> Add inside if fixture

- rules-tests/DowngradePhp70/Rector/Spaceship/DowngradeSpaceshipRector/Fixture/ternary_spaceship_nested.php.inc
- rules-tests/DowngradePhp70/Rector/Spaceship/DowngradeSpaceshipRector/config/php_70.php
- rules/DowngradePhp70/Rector/Spaceship/DowngradeSpaceshipRector.php
Follow up to https://github.com/rectorphp/rector-downgrade-php/pull/78
> Spaceship post fix

- phpstan.neon
- rules-tests/DowngradePhp71/Rector/StaticCall/DowngradeClosureFromCallableRector/Fixture/on_return.php.inc
- rules/DowngradePhp71/Rector/StaticCall/DowngradeClosureFromCallableRector.php
Continue of PR:
- https://github.com/rectorphp/rector-downgrade-php/pull/76
> [DowngradePhp71] Add Return_ support on DowngradeClosureFromCallableRector

- rules/DowngradePhp70/Rector/FuncCall/DowngradeDirnameLevelsRector.php
- rules/DowngradePhp70/Rector/FuncCall/DowngradeSessionStartArrayOptionsRector.php
- rules/DowngradePhp70/Rector/FuncCall/DowngradeUncallableValueCallToCallUserFuncRector.php
- rules/DowngradePhp70/Rector/MethodCall/DowngradeClosureCallRector.php
- rules/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector.php
- rules/DowngradePhp71/Rector/FuncCall/DowngradeIsIterableRector.php
- rules/DowngradePhp71/Rector/StaticCall/DowngradeClosureFromCallableRector.php
- rules/DowngradePhp72/NodeAnalyzer/FunctionExistsFunCallAnalyzer.php
- rules/DowngradePhp72/NodeManipulator/BitwiseFlagCleaner.php
- rules/DowngradePhp72/Rector/FuncCall/DowngradeStreamIsattyRector.php
- rules/DowngradePhp73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector.php
- rules/DowngradePhp73/Rector/FuncCall/DowngradeIsCountableRector.php
- rules/DowngradePhp73/Rector/FuncCall/DowngradeTrailingCommasInFunctionCallsRector.php
- rules/DowngradePhp73/Rector/FuncCall/SetCookieOptionsArrayToArgumentsRector.php
- rules/DowngradePhp74/Rector/FuncCall/DowngradeStripTagsCallWithArrayRector.php
- rules/DowngradePhp80/Rector/FuncCall/DowngradeStrContainsRector.php
- rules/DowngradePhp81/NodeManipulator/ObjectToResourceReturn.php
- rules/DowngradePhp81/Rector/FuncCall/DowngradeArrayIsListRector.php
- rules/DowngradePhp81/Rector/FuncCall/DowngradeEnumExistsRector.php
Fixes https://github.com/rectorphp/rector/issues/7969
> Fix getArgs() usage as Arg function that cause by reference error

- rules-tests/DowngradePhp81/Rector/FuncCall/DowngradeArrayIsListRector/Fixture/inside_if.php.inc
- rules-tests/DowngradePhp81/Rector/FuncCall/DowngradeArrayIsListRector/Fixture/inside_return.php.inc
- rules/DowngradePhp81/Rector/FuncCall/DowngradeArrayIsListRector.php
Ref https://github.com/rectorphp/rector/commit/075297ce566b61c9d4984e50d4e6520af7054977#diff-b01ffcf2f181bc4f607a1f0114af890c69aea17e4c0a8128b2fec550eefa7765
>  [DowngradePhp81] Handle inside If cond on DowngradeArrayIsListRector 

- rules-tests/DowngradePhp71/Rector/StaticCall/DowngradeClosureFromCallableRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp71/Rector/StaticCall/DowngradeClosureFromCallableRector/Fixture/on_return_inside_array.php.inc
- rules/DowngradePhp71/Rector/StaticCall/DowngradeClosureFromCallableRector.php
Ref https://github.com/rectorphp/rector/issues/7975
> [DowngradePhp71] Use ExprInTopStmtMatcher on DowngradeClosureFromCallableRector

- rules/DowngradePhp70/Rector/Spaceship/DowngradeSpaceshipRector.php
- rules/DowngradePhp71/Rector/StaticCall/DowngradeClosureFromCallableRector.php
- rules/DowngradePhp80/Rector/New_/DowngradeArbitraryExpressionsSupportRector.php
- src/NodeFactory/NamedVariableFactory.php
Passed current Stmt instead of parent lookup to get current stmt on NamedVariableFactory
> [NodeFactory] Remove parent lookup on NamedVariableFactory

- rules-tests/DowngradePhp73/Rector/ConstFetch/DowngradePhp73JsonConstRector/Fixture/deifferent_define_check.php.inc
- rules-tests/DowngradePhp73/Rector/ConstFetch/DowngradePhp73JsonConstRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp73/Rector/ConstFetch/DowngradePhp73JsonConstRector/Fixture/in_bitwise.php.inc
- rules-tests/DowngradePhp73/Rector/ConstFetch/DowngradePhp73JsonConstRector/Fixture/skip_bitwise_different_constants.php.inc
- rules-tests/DowngradePhp73/Rector/ConstFetch/DowngradePhp73JsonConstRector/Fixture/skip_different_constant.php.inc
- rules-tests/DowngradePhp73/Rector/ConstFetch/DowngradePhp73JsonConstRector/Fixture/skip_inside_define_check.php.inc
- rules/DowngradePhp71/Rector/ConstFetch/DowngradePhp71JsonConstRector.php
- rules/DowngradePhp72/NodeManipulator/JsonConstCleaner.php
- rules/DowngradePhp72/Rector/ConstFetch/DowngradePhp72JsonConstRector.php
- rules/DowngradePhp73/Rector/ConstFetch/DowngradePhp73JsonConstRector.php
- rules/DowngradePhp80/Rector/Expression/DowngradeThrowExprRector.php
- src/NodeAnalyzer/DefineFuncCallAnalyzer.php
- remove defined check
- cleanup
> Remove PARENT_NODE from DowngradePhp73JsonConstRector

- rules/DowngradePhp80/Rector/MethodCall/DowngradeReflectionGetAttributesRector.php
Ref https://github.com/rectorphp/rector-downgrade-php/pull/108#pullrequestreview-1473693651
> [DowngradePhp80] Remove direct return STOP_TRAVERSAL on refactor() on DowngradeReflectionGetAttributesRector

- rules/DowngradePhp80/Rector/ClassMethod/DowngradeRecursiveDirectoryIteratorHasChildrenRector.php
Ref https://github.com/rectorphp/rector/issues/7947
> [Downgradephp80] Remove findParentType() on DowngradeRecursiveDirectoryIteratorHasChildrenRector

- rules/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector.php
PR:
- https://github.com/rectorphp/rector-downgrade-php/pull/117
cause error https://github.com/rectorphp/rector-src/actions/runs/5247905373/jobs/9478683938
> Update php doc info after update param on ClassMethod

- composer.json
- rules/DowngradePhp71/Rector/FunctionLike/DowngradeNullableTypeDeclarationRector.php
- rules/DowngradePhp72/PhpDoc/NativeParamToPhpDocDecorator.php
- rules/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector.php
- rules/DowngradePhp74/Rector/ClassMethod/DowngradeContravariantArgumentTypeRector.php
- rules/DowngradePhp74/Rector/ClassMethod/DowngradeCovariantReturnTypeRector.php
- rules/DowngradePhp80/Rector/Class_/DowngradePropertyPromotionRector.php
- src/NodeManipulator/PropertyDecorator.php
- src/PhpDocDecorator/PhpDocFromTypeDeclarationDecorator.php
Ref https://github.com/rectorphp/rector-src/pull/4215
> Update PhpDocTypeChanger call arguments usage per use of DocblockUpdater

- rules-tests/DowngradePhp74/Rector/ArrowFunction/ArrowFunctionToAnonymousFunctionRector/Fixture/return_assign.php.inc
- rules-tests/DowngradePhp74/Rector/ArrowFunction/ArrowFunctionToAnonymousFunctionRector/Source/Foo.php
- rules/DowngradePhp74/Rector/ArrowFunction/ArrowFunctionToAnonymousFunctionRector.php
Fixes https://github.com/rectorphp/rector/issues/7990
> [DowngradePhp743] Handle return assign on ArrowFunctionToAnonymousFunctionRector

- rules/DowngradePhp73/Rector/ConstFetch/DowngradePhp73JsonConstRector.php
https://github.com/rectorphp/rector-downgrade-php/pull/133#pullrequestreview-1490524033
> [DowngradePhp73] Refactor DowngradePhp73JsonConstRector so downgrade-able

- .github/workflows/code_analysis.yaml
- .github/workflows/code_analysis_reusable.yaml
- composer.json
Ref https://tomasvotruba.com/blog/how-to-avoid-maintaining-classes-you-dont-use
> Add class-leak to CI

- rules/DowngradePhp74/Rector/ClassMethod/DowngradeContravariantArgumentTypeRector.php
to ensure it shown on Applied rules and node scope refreshed.
> [DowngradePhp74] Use $hasChanged flag on DowngradeContravariantArgumentTypeRector on node changed

- rules/DowngradePhp80/Rector/StaticCall/DowngradePhpTokenRector.php
Ref https://getrector.com/blog/faster-rector-on-015
> [Performance] avoid object type creation when possible on DowngradePhpTokenRector

- composer.json
- config/set/downgrade-php81.php
Fixes https://github.com/TomasVotruba/phpunit-10-for-php-8/commit/2c20f27bc37294e023fad8ec04b02df95c3b296d
Failing CI fix will follow :+1:
> [PHP 8.1] Downgrade tenative type on function reflection

- config/set/downgrade-php81.php
- docs/rector_rules_overview.md
- rules-tests/DowngradePhp81/Rector/MethodCall/DowngradeIsEnumRector/DowngradeIsEnumRectorTest.php
- rules-tests/DowngradePhp81/Rector/MethodCall/DowngradeIsEnumRector/Fixture/some_class.php.inc
- rules-tests/DowngradePhp81/Rector/MethodCall/DowngradeIsEnumRector/config/configured_rule.php
- rules/DowngradePhp81/Rector/MethodCall/DowngradeIsEnumRector.php
Fixes https://github.com/TomasVotruba/phpunit-10-for-php-8/commit/e399dd815472f3a5c76da04dd44c1c5d31ecfae0
> [PHP 8.1] Add DowngradeIsEnumRector

- rules/DowngradePhp81/Rector/MethodCall/DowngradeIsEnumRector.php
Ref https://getrector.com/blog/faster-rector-on-015
> Avoid create new Object when not isEnum() method on owngradeIsEnumRector

- rules/DowngradePhp74/Rector/ClassMethod/DowngradeContravariantArgumentTypeRector.php
- rules/DowngradePhp74/Rector/ClassMethod/DowngradeCovariantReturnTypeRector.php
Ref https://github.com/rectorphp/rector-src/pull/5091
> Move pull StaticTypeMapper from AbstractRector into rules

- docs/rector_rules_overview.md
- rules-tests/DowngradePhp74/Rector/FuncCall/DowngradeProcOpenArrayCommandArgRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp74/Rector/FuncCall/DowngradeProcOpenArrayCommandArgRector/Fixture/non_variable.php.inc
- rules/DowngradePhp74/Rector/FuncCall/DowngradeProcOpenArrayCommandArgRector.php
Fixes https://github.com/rectorphp/rector-downgrade-php/issues/198
> [DowngradePhp74] Ensure use escapeshellarg() on DowngradeProcOpenArrayCommandArgRector

- rules-tests/DowngradePhp80/Rector/StaticCall/DowngradePhpTokenRector/Fixture/name_id_to_integer_index.php.inc
- rules/DowngradePhp80/Rector/StaticCall/DowngradePhpTokenRector.php
@TomasVotruba this should fix https://github.com/rectorphp/getrector-com/issues/2142 fix https://github.com/rectorphp/rector/issues/8565
> [DowngradePhp80] Fix downgrade PhpToken::tokenize() and call with ->id

- composer.json
- rules-tests/DowngradePhp80/Rector/FunctionLike/DowngradeUnionTypeDeclarationRector/Fixture/keep_nullable_trio_docblock.php.inc
in favor of https://github.com/rectorphp/rector-src/pull/5792
> Use sorted union types doc by phpstan DowngradeUnionTypeDeclarationRector

- composer.json
Ref https://github.com/rectorphp/rector-src/pull/5847
> Bump class-leak to ^0.2.13

- composer.json
- tests/Issues/IssueDowngradeParamType/FixtureDownToPhp71/downgrade_param_reflection_get_attribute.php.inc
This for require by PR:
- https://github.com/rectorphp/rector-src/pull/5911
> Update auto import fixture on downgrade param type

- rules/DowngradePhp80/NodeAnalyzer/UnnamedArgumentResolver.php
Ref https://github.com/rectorphp/rector/issues/8843
> Fix deprecated ParametersAcceptorSelector::selectSingle() since PHPStan 1.12.5

- composer.json
- rules/DowngradePhp81/Rector/Property/DowngradeReadonlyPropertyRector.php
- src/Set/ValueObject/DowngradeLevelSetList.php
- src/Set/ValueObject/DowngradeSetList.php
Ref https://github.com/rectorphp/rector-src/pull/5976
> Remove deprecated set list marker

- rules/DowngradePhp80/Rector/StaticCall/DowngradePhpTokenRector.php
Ref https://github.com/rectorphp/rector-src/pull/6431#issuecomment-2489079041
> Fix ThisType extends PhpParser\Internal\TokenPolyfill on DowngradePhpTokenRector

- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeTrailingCommasInFunctionCallsRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeTrailingCommasInFunctionCallsRector/Fixture/multi_space.php.inc
- rules-tests/DowngradePhp73/Rector/FuncCall/DowngradeTrailingCommasInFunctionCallsRector/Fixture/new.php.inc
- rules/DowngradePhp73/Rector/FuncCall/DowngradeTrailingCommasInFunctionCallsRector.php
- tests/Issues/DowngradeHeredoc/DowngradeHeredocTest.php
- tests/Issues/DowngradeHeredoc/Fixture/fixture.php.inc
- tests/Issues/DowngradeHeredoc/config/configured_rule.php
@@Moskito89 Continue of PR:
- https://github.com/rectorphp/rector-downgrade-php/pull/256
here for multi rules apply.
Ref https://github.com/easy-coding-standard/easy-coding-standard/issues/245#issuecomment-2539044213
> [DowngradePhp73] Handle heredoc new line stripped on multi rules

- rules/DowngradePhp73/Rector/FuncCall/DowngradeTrailingCommasInFunctionCallsRector.php
- tests/Issues/DowngradeHeredoc/Fixture/next_arg.php.inc
@Moskito89 Continue of PR: 
- https://github.com/rectorphp/rector-downgrade-php/pull/257
fix another issue https://github.com/easy-coding-standard/easy-coding-standard/actions/runs/12299002716/job/34323755316#step:12:950
> Fix complex next arg

- composer.json
- rules/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector.php
- src/PhpDocDecorator/PhpDocFromTypeDeclarationDecorator.php
Ref 
- https://github.com/rectorphp/rector-src/pull/6775
> Change deprecated ClassReflection::isSubClassOf() to ClassReflection::is() for PHPStan ^2.1.8

- composer.json
Ref merged PR: 
- https://github.com/rectorphp/rector-src/pull/6879
> Back to use rector-src:dev-main

- config/set/downgrade-php80.php
- rules-tests/DowngradePhp80/Rector/Instanceof_/DowngradeInstanceofStringableRector/DowngradeInstanceofStringableRectorTest.php
- rules-tests/DowngradePhp80/Rector/Instanceof_/DowngradeInstanceofStringableRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp80/Rector/Instanceof_/DowngradeInstanceofStringableRector/Fixture/skip_different_object.php.inc
- rules-tests/DowngradePhp80/Rector/Instanceof_/DowngradeInstanceofStringableRector/config/configured_rule.php
- rules/DowngradePhp80/Rector/Instanceof_/DowngradeInstanceofStringableRector.php
Fixes https://github.com/rectorphp/rector-downgrade-php/issues/219
> [DowngradePhp80] Add DowngradeInstanceofStringableRector

- rules-tests/DowngradePhp81/Rector/StmtsAwareInterface/DowngradeSetAccessibleReflectionPropertyRector/Fixture/on_reflection_method.php.inc
- rules/DowngradePhp81/Rector/StmtsAwareInterface/DowngradeSetAccessibleReflectionPropertyRector.php
Ref
- https://github.com/rectorphp/rector-src/pull/7085
> [DowngradePhp81] Allow downgrade ReflectionMethod on DowngradeSetAccessibleReflectionPropertyRector

- rules-tests/DowngradePhp84/Rector/Expression/DowngradeArrayAllRector/Fixture/on_return.php.inc
- rules/DowngradePhp74/Rector/ArrowFunction/ArrowFunctionToAnonymousFunctionRector.php
- rules/DowngradePhp84/Rector/Expression/DowngradeArrayAllRector.php
This is example on handle downgrade `return array_all()` without assignment.
>  [DowngradePhp84] Apply on return on DowngradeArrayAllRector 

- rules-tests/DowngradePhp85/Rector/Class_/DowngradeFinalPropertyPromotionRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp85/Rector/Class_/DowngradeFinalPropertyPromotionRector/Fixture/implicit_final_property_promotion.php.inc
- rules-tests/DowngradePhp85/Rector/Class_/DowngradeFinalPropertyPromotionRector/Fixture/skip_fixture_readonly.php.inc
- rules/DowngradePhp85/Rector/Class_/DowngradeFinalPropertyPromotionRector.php
@arshidkv12 this is to handle implicit public on ref https://github.com/rectorphp/rector-downgrade-php/pull/317#pullrequestreview-3196636259
> [DowngradePhp85] Handle implicit public on DowngradeFinalPropertyPromotionRector

- rules-tests/DowngradePhp83/Rector/FuncCall/DowngradeJsonValidateRector/Fixture/with_first_class_callable.php.inc
- rules/DowngradePhp83/Rector/FuncCall/DowngradeJsonValidateRector.php
Ref https://github.com/rectorphp/rector/issues/9367
> [DowngradePhp83] Allow with first class callable on DowngradeJsonValidateRector

- rules-tests/DowngradePhp82/Rector/FuncCall/DowngradeIteratorCountToArrayRector/Fixture/with_named_arg.php.inc
- rules/DowngradePhp82/Rector/FuncCall/DowngradeIteratorCountToArrayRector.php
Ref https://github.com/rectorphp/rector/issues/9386
> [DowngradePhp82] Allow with named argument on DowngradeIteratorCountToArrayRector

- rules-tests/DowngradePhp84/Rector/FuncCall/DowngradeRoundingModeEnumRector/Fixture/with_named_arg.php.inc
- rules/DowngradePhp84/Rector/FuncCall/DowngradeRoundingModeEnumRector.php
Ref https://github.com/rectorphp/rector/issues/9386
> [DowngradePhp84] Allow named arg on DowngradeRoundingModeEnumRector

- rules/DowngradePhp81/Rector/FuncCall/DowngradeHashAlgorithmXxHashRector.php
- rules/DowngradePhp82/Rector/FuncCall/DowngradeIteratorCountToArrayRector.php
Ref https://github.com/rectorphp/rector-src/pull/7409
> Update rules @return to use specific NodeVisitor:: constant per latest PHPStan
